version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bidi_postgres
    environment:
      POSTGRES_USER: bidi_user
      POSTGRES_PASSWORD: bidi
      POSTGRES_DB: bidi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: